name: Test and maybe deploy

on:
  push:
    branches:
      - main
  pull_request:

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_WORKSPACE }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  FABRIC_NAME: ${{ secrets.FABRIC_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # Install all python dependencies 
      # prophecy-libs not included here because prophecy-build-tool 
      # takes care of it by reading each pipeline's setup.py
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install build pytest wheel pytest-html pyspark prophecy-build-tool
      - name: Run PBT build
        run: pbt build --path hello_world
      - name: Run PBT test
        run: pbt test --path hello_world
      - name: Deploy to environment (if merging to main)
        run: pbt deploy --path hello_world
        if: github.ref == 'refs/heads/main'